name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest  

    steps:
    - name: Clônage du dépôt GIT
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configuration de .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Obtention des dépendances
      run: dotnet restore
    - name: Compilation
      run: dotnet build --no-restore
    - name: Exécution des tests unitaires
      run: dotnet test --no-build --verbosity normal
    - name: Génération du GitHub Issue
      if: failure()
      uses: actions/github-script@v5
      with:
        script: |
          const { owner, repo } = context.repo;
          const title = `Tests failed on PR #${context.issue.number}`;
          const body = `The tests have failed for this PR. Please review the changes.`;
          github.issues.create({
            owner,
            repo,
            title,
            body,
          });